[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

# This is the name of your project
name = "Aivancity Assistant"

# This is the description of your project
description = "AI-powered assistant for Aivancity School"

# This is the URL of your project
url = "https://github.com/Harold-debug/gen_ai_project_chatbot"

# This is the path to your project's icon
icon = "🏫"

# This is the path to your project's logo
logo = "🏫"

# This is the path to your project's favicon
favicon = "🏫"

# This is the path to your project's custom CSS
custom_css = ""

# This is the path to your project's custom JS
custom_js = ""

# This is the path to your project's custom HTML
custom_html = ""

# This is the path to your project's custom components
custom_components = ""

# This is the path to your project's custom pages
custom_pages = ""

# This is the path to your project's custom translations
custom_translations = ""

# This is the path to your project's custom themes
custom_themes = ""

# This is the path to your project's custom locales
custom_locales = ""

# This is the path to your project's custom middleware
custom_middleware = ""

# This is the path to your project's custom routes
custom_routes = ""

# This is the path to your project's custom static files
custom_static = ""

# This is the path to your project's custom templates
custom_templates = ""

# This is the path to your project's custom views
custom_views = ""

# This is the path to your project's custom models
custom_models = ""

# This is the path to your project's custom forms
custom_forms = ""

# This is the path to your project's custom validators
custom_validators = ""

# This is the path to your project's custom serializers
custom_serializers = ""

# This is the path to your project's custom permissions
custom_permissions = ""

# This is the path to your project's custom authentication
custom_auth = ""

# This is the path to your project's custom authorization
custom_authorization = ""

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = false

# Authorized origins
allow_origins = ["*"]

# Follow symlink for asset mount (see https://github.com/Chainlit/chainlit/issues/317)
# follow_symlink = false

[features]
# Process and display HTML in messages. This can be a security risk (see https://stackoverflow.com/questions/19603097/why-is-it-dangerous-to-render-user-generated-html-or-javascript)
unsafe_allow_html = false

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

# Automatically tag threads with the current chat profile (if a chat profile is used)
auto_tag_thread = true

# Allow users to edit their own messages
edit_message = true

# Authorize users to spontaneously upload files with messages
[features.spontaneous_file_upload]
    enabled = true
    accept = ["*/*"]
    max_files = 20
    max_size_mb = 500

# Enable or disable features
multi_modal = true
persist_chat = true
show_actions = true
show_avatars = true
show_typing = true
show_thoughts = true
show_source = true
show_metadata = true

[UI]
# Name of the assistant.
name = "Aivancity Assistant"

# Description of the assistant. This is used for HTML tags.
description = "Your AI-powered assistant for Aivancity School"

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# Chain of Thought (CoT) display mode. Can be "hidden", "tool_call" or "full".
cot = "full"

# Link to your github repo. This will add a github button in the UI's header.
# github = ""

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
# custom_css = "/public/test.css"

# Specify a Javascript file that can be used to customize the user interface.
# The Javascript file can be served from the public directory.
# custom_js = "/public/test.js"

# Specify a custom font url.
# custom_font = "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap"

# Specify a custom meta image url.
# custom_meta_image_url = "https://chainlit-cloud.s3.eu-west-3.amazonaws.com/logo/chainlit_banner.png"

# Specify a custom build directory for the frontend.
# This can be used to customize the frontend code.
# Be careful: If this is a relative path, it should not start with a slash.
# custom_build = "./public/build"

# Theme configuration
[UI.theme]
    default = "light"
    primary_color = "#4F46E5"
    background_color = "#FFFFFF"
    font_family = "Inter"

# Override default MUI light theme. (Check theme.ts)
[UI.theme.light]
    #background = "#FAFAFA"
    #paper = "#FFFFFF"

    [UI.theme.light.primary]
        #main = "#F80061"
        #dark = "#980039"
        #light = "#FFE7EB"
    [UI.theme.light.text]
        #primary = "#212121"
        #secondary = "#616161"

# Override default MUI dark theme. (Check theme.ts)
[UI.theme.dark]
    #background = "#FAFAFA"
    #paper = "#FFFFFF"

    [UI.theme.dark.primary]
        #main = "#F80061"
        #dark = "#980039"
        #light = "#FFE7EB"
    [UI.theme.dark.text]
        #primary = "#EEEEEE"
        #secondary = "#BDBDBD"

[meta]
generated_by = "1.3.2"

[ui]
# UI configuration
theme = "light"
primary_color = "#4F46E5"
background_color = "#FFFFFF"
font_family = "Inter"
chat_avatar_size = 40
message_spacing = 24
message_padding = 12
message_border_radius = 8
message_background_color = "#F3F4F6"
user_message_background_color = "#4F46E5"
user_message_text_color = "#FFFFFF"
assistant_message_background_color = "#F3F4F6"
assistant_message_text_color = "#1F2937"

[security]
# Security configuration
auth = true
auth_username = "admin"
auth_password = "aivancity"

# Custom login page configuration
[security.login]
    title = "Welcome to Aivancity Assistant"
    subtitle = "Please login to continue"
    logo = "🏫"
    background_color = "#F3F4F6"
    text_color = "#1F2937"
    button_color = "#4F46E5"
    button_text_color = "#FFFFFF"
